const DJINN_SPRITES = {
    goldensun: {
        venus: require('../assets/images/goldensun/venus_djinni.png'),
        mars: require('../assets/images/goldensun/mars_djinni.png'),
        jupiter: require('../assets/images/goldensun/jupiter_djinni.png'),
        mercury: require('../assets/images/goldensun/mercury_djinni.png'),
    },
    lostage: {
        venus: require('../assets/images/goldensun/venus_djinni.png'),
        mars: require('../assets/images/goldensun/mars_djinni.png'),
        jupiter: require('../assets/images/goldensun/jupiter_djinni.png'),
        mercury: require('../assets/images/goldensun/mercury_djinni.png'),
        zagan: require('../assets/images/lostage/zagan.png'),
        megaera: require('../assets/images/lostage/megaera.png'),
        flora: require('../assets/images/lostage/flora.png'),
        moloch: require('../assets/images/lostage/moloch.png'),
        ulysses: require('../assets/images/lostage/ulysses.png'),
        eclipse: require('../assets/images/lostage/eclipse.png'),
        haures: require('../assets/images/lostage/haures.png'),
        coatlicue: require('../assets/images/lostage/coatlicue.png'),
        azul: require('../assets/images/lostage/azul.png'),
        daedalus: require('../assets/images/lostage/daedalus.png'),
        catastrophe: require('../assets/images/lostage/catastrophe.png'),
        charon: require('../assets/images/lostage/charon.png'),
        iris: require('../assets/images/lostage/iris.png'),
    },
    darkdawn: {
        flint: require('../assets/images/darkdawn/flint.png'),
        flower: require('../assets/images/darkdawn/flower.png'),
        bark: require('../assets/images/darkdawn/bark.png'),
        steel: require('../assets/images/darkdawn/steel.png'),
        brick: require('../assets/images/darkdawn/brick.png'),
        vine: require('../assets/images/darkdawn/vine.png'),
        gears: require('../assets/images/darkdawn/gears.png'),
        furrow: require('../assets/images/darkdawn/furrow.png'),
        garland: require('../assets/images/darkdawn/garland.png'),
        pewter: require('../assets/images/darkdawn/pewter.png'),
        chasm: require('../assets/images/darkdawn/chasm.png'),
        chain: require('../assets/images/darkdawn/chain.png'),
        buckle: require('../assets/images/darkdawn/buckle.png'),
        clover: require('../assets/images/darkdawn/clover.png'),
        magnet: require('../assets/images/darkdawn/magnet.png'),
        geode: require('../assets/images/darkdawn/geode.png'),
        ivy: require('../assets/images/darkdawn/ivy.png'),
        hemlock: require('../assets/images/darkdawn/hemlock.png'),

        forge: require('../assets/images/darkdawn/forge.png'),
        fever: require('../assets/images/darkdawn/fever.png'),
        cinder: require('../assets/images/darkdawn/cinder.png'),
        lava: require('../assets/images/darkdawn/lava.png'),
        brand: require('../assets/images/darkdawn/brand.png'),
        fury: require('../assets/images/darkdawn/fury.png'),
        glare: require('../assets/images/darkdawn/glare.png'),
        reflux: require('../assets/images/darkdawn/reflux.png'),
        wrath: require('../assets/images/darkdawn/wrath.png'),
        chili: require('../assets/images/darkdawn/chili.png'),
        glow: require('../assets/images/darkdawn/glow.png'),
        stoke: require('../assets/images/darkdawn/stoke.png'),
        sizzle: require('../assets/images/darkdawn/sizzle.png'),
        pepper: require('../assets/images/darkdawn/pepper.png'),
        tinder: require('../assets/images/darkdawn/tinder.png'),
        flare: require('../assets/images/darkdawn/flare.png'),
        fugue: require('../assets/images/darkdawn/fugue.png'),
        aurora: require('../assets/images/darkdawn/aurora.png'),

        gust: require('../assets/images/darkdawn/gust.png'),
        jolt: require('../assets/images/darkdawn/jolt.png'),
        ether: require('../assets/images/darkdawn/ether.png'),
        breath: require('../assets/images/darkdawn/breath.png'),
        vortex: require('../assets/images/darkdawn/vortex.png'),
        doldrum: require('../assets/images/darkdawn/doldrum.png'),
        fleet: require('../assets/images/darkdawn/fleet.png'),
        waft: require('../assets/images/darkdawn/waft.png'),
        bolt: require('../assets/images/darkdawn/bolt.png'),
        breeze: require('../assets/images/darkdawn/breeze.png'),
        haze: require('../assets/images/darkdawn/haze.png'),
        sirocco: require('../assets/images/darkdawn/sirocco.png'),
        wisp: require('../assets/images/darkdawn/wisp.png'),
        puff: require('../assets/images/darkdawn/puff.png'),
        kite: require('../assets/images/darkdawn/kite.png'),
        swift: require('../assets/images/darkdawn/swift.png'),
        simoom: require('../assets/images/darkdawn/simoom.png'),
        lull: require('../assets/images/darkdawn/lull.png'),

        chill: require('../assets/images/darkdawn/chill.png'),
        sleet: require('../assets/images/darkdawn/sleet.png'),
        surge: require('../assets/images/darkdawn/surge.png'),
        mist: require('../assets/images/darkdawn/mist.png'),
        mellow: require('../assets/images/darkdawn/mellow.png'),
        claw: require('../assets/images/darkdawn/claw.png'),
        serac: require('../assets/images/darkdawn/serac.png'),
        dewdrop: require('../assets/images/darkdawn/dewdrop.png'),
        torrent: require('../assets/images/darkdawn/torrent.png'),
        spout: require('../assets/images/darkdawn/spout.png'),
        coral: require('../assets/images/darkdawn/coral.png'),
        teardrop: require('../assets/images/darkdawn/teardrop.png'),
        pincer: require('../assets/images/darkdawn/pincer.png'),
        spring: require('../assets/images/darkdawn/spring.png'),
        shell: require('../assets/images/darkdawn/shell.png'),
        rime: require('../assets/images/darkdawn/rime.png'),
        geyser: require('../assets/images/darkdawn/geyser.png'),
        foam: require('../assets/images/darkdawn/foam.png'),

        zagan: require('../assets/images/darkdawn/zagan.png'),
        megaera: require('../assets/images/darkdawn/megaera.png'),
        flora: require('../assets/images/darkdawn/flora.png'),
        moloch: require('../assets/images/darkdawn/moloch.png'),
        ulysses: require('../assets/images/darkdawn/ulysses.png'),
        haures: require('../assets/images/darkdawn/haures.png'),
        eclipse: require('../assets/images/darkdawn/eclipse.png'),
        crystallux: require('../assets/images/darkdawn/crystallux.png'),
        coatlicue: require('../assets/images/darkdawn/coatlicue.png'),
        azul: require('../assets/images/darkdawn/azul.png'),
        daedalus: require('../assets/images/darkdawn/daedalus.png'),
        catastrophe: require('../assets/images/darkdawn/catastrophe.png'),
        charon: require('../assets/images/darkdawn/charon.png'),
        iris: require('../assets/images/darkdawn/iris.png')
    }
}

const GAME_LOGOS = {
    goldensun: require('../assets/images/goldensun_logo.png'),
    lostage: require('../assets/images/thelostage_logo.png'),
    darkdawn: require('../assets/images/darkdawn_logo.png'),
}

export const retrieveLogo = (game) => {
    return GAME_LOGOS[game];
}

export const retrieveSprite = (game, file) => {
    if (!game in DJINN_SPRITES) {
        // game does not exist
        return undefined;
    }
    return DJINN_SPRITES[game][file];
}
